---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: home-assistant-pv
  namespace: home-assistant
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-client
  nfs:
    path: 192.168.1.155
    server: /nfs/k3s/home-assistant