---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-pvc
  namespace: home-assistant
spec:
  volumeMode: Filesystem
  storageClassName: nfs-client
  volumeName: home-assistant-pv
  resources:
    requests:
      storage: 2Gi
  accessModes:
    - ReadWriteOnce