apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd
  namespace: argocd
spec:
  ingressClassName: traefik
  rules:
  - host: argocd.crimsyn.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argocd
            port:
              number: 80
