---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homarr-data-pvc
  namespace: homarr
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  volumeName: homarr-data-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homarr-configs-pvc
  namespace: homarr
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  volumeName: homarr-configs-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homarr-icons-pvc
  namespace: homarr
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  volumeName: homarr-icons-pv
